/*
 * Copyright (c) 1993, 1994, 1995, 1996, 1997, 1998
 *	The Regents of the University of California.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *	This product includes software developed by the Computer Systems
 *	Engineering Group at Lawrence Berkeley Laboratory.
 * 4. Neither the name of the University nor of the Laboratory may be used
 *    to endorse or promote products derived from this software without
 *    specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include <pcap/pcap.h>

/*
 * This function is needed because it is called by onefile.c, which
 * is linked into the fuzzers in this project.
 */
void fuzz_openFile(const char *name) {
    (void)name;
}

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    /*
     * We need enough data for the parameters of pcap_open_dead and
     * pcap_compile.
     * linktype (2 bytes), snaplen (2 bytes), optimize (1 byte), mask (4 bytes)
     * Total = 9 bytes.
     */
    if (size < 10) {
        return 0;
    }

    // Extract parameters from fuzz data
    int linktype = data[0] | (data[1] << 8);
    int snaplen = data[2] | (data[3] << 8);
    int optimize = data[4] & 1;
    
    // Mask for pcap_compile
    uint32_t mask;
    memcpy(&mask, data + 5, 4);
    
    // The remaining data is treated as the filter expression string
    size_t filter_size = size - 9;
    char *filter = (char *)malloc(filter_size + 1);
    if (filter == NULL) {
        return 0;
    }
    memcpy(filter, data + 9, filter_size);
    filter[filter_size] = '\0';

    /*
     * pcap_compile() requires a non-zero snaplen. If it's 0, it will return
     * an error immediately, which doesn't exercise the compiler logic.
     */
    if (snaplen <= 0) {
        snaplen = 65535;
    }

    /*
     * Create a "dead" pcap_t for offline compilation.
     * linktype specifies the link-layer header type (e.g. DLT_EN10MB).
     */
    pcap_t *p = pcap_open_dead(linktype, snaplen);
    if (p != NULL) {
        struct bpf_program fp;
        /*
         * Compile the filter expression into BPF bytecode.
         * This is the core of the BPF compiler.
         */
        if (pcap_compile(p, &fp, filter, optimize, mask) == 0) {
            // If compilation succeeded, free the generated bytecode
            pcap_freecode(&fp);
        }
        // Always close the pcap handle
        pcap_close(p);
    }

    // Clean up the filter string buffer
    free(filter);

    return 0;
}
