/*
 * fuzz_dga.c
 *
 * Copyright (C) 2011-24 - ntop.org
 *
 * This file is part of nDPI, an open source deep packet inspection
 * library based on the OpenDPI and PACE technology by ipoque GmbH
 *
 * nDPI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

#include "ndpi_api.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libgen.h>

/*
 * Global detection module structure, initialized once and shared across fuzzing iterations.
 */
static struct ndpi_detection_module_struct *ndpi_struct = NULL;
static char *bin_path = NULL;

/*
 * Custom DGA prediction function to increase library coverage by testing custom logic path.
 */
static int ndpi_custom_dga_fn(const char* domain, int domain_length) {
    if(!domain) return 0;
    return ndpi_is_printable_buffer((const u_int8_t *)domain, (size_t)domain_length);
}

/*
 * Initialization function for libFuzzer. Sets up the path to external data files.
 */
int LLVMFuzzerInitialize(int *argc, char ***argv) {
    if (*argc > 0) {
        char *exe_path = strdup((*argv)[0]);
        if (exe_path) {
            char *dir = dirname(exe_path);
            if (dir) {
                bin_path = strdup(dir);
            }
            free(exe_path);
        }
    }
    return 0;
}

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    /* Minimum size to allow choosing a custom DGA function and have a name string */
    if (size < 2 || size > 1024)
        return 0;

    /* Initialize the nDPI detection module once */
    if (ndpi_struct == NULL) {
        ndpi_struct = ndpi_init_detection_module(NULL);
        if (ndpi_struct == NULL) return 0;

        /* Load domain suffixes to improve DGA detection accuracy if the file is available */
        if (bin_path) {
            char suffix_path[512];
            snprintf(suffix_path, sizeof(suffix_path), "%s/public_suffix_list.dat", bin_path);
            ndpi_load_domain_suffixes(ndpi_struct, suffix_path);
        }
        
        ndpi_finalize_initialization(ndpi_struct);
    }

    /* Toggle custom DGA function based on the first byte of input */
    ndpi_dga_function = (data[0] % 2 == 0) ? ndpi_custom_dga_fn : NULL;

    /* Create a fresh flow structure for each input to ensure state isolation */
    struct ndpi_flow_struct *ndpi_flow = (struct ndpi_flow_struct *)ndpi_calloc(1, sizeof(struct ndpi_flow_struct));
    if (ndpi_flow == NULL) return 0;

    /* The target function expects a null-terminated string */
    char *name = (char *)ndpi_malloc(size + 1);
    if (name) {
        memcpy(name, data, size);
        name[size] = '\0';
        
        /* 
         * Check if the provided name is likely generated by a DGA.
         * Parameters:
         * - ndpi_struct: The detection module
         * - ndpi_flow: Flow state where results/risks are stored
         * - name: The domain name to evaluate
         * - is_hostname: 1 (typically true for SNI/Host headers)
         * - check_subproto: 1 (to match against known subprotocols)
         * - flow_fully_classified: 0 (allow checking even for new flows)
         */
        ndpi_check_dga_name(ndpi_struct, ndpi_flow, name, 1, 1, 0);
        
        ndpi_free(name);
    }

    /* Clean up per-flow resources */
    ndpi_free_flow_data(ndpi_flow);
    ndpi_free(ndpi_flow);

    return 0;
}
